services:
  db:
    image: postgres:16
    container_name: fido2-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: fido2-backend
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: fido2-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend

  gateway:
    image: caddy:2
    container_name: fido2-gateway
    restart: unless-stopped
    ports:
      - "8081:8080"
    volumes:
      - ./gateway/Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - backend
      - frontend

volumes:
  db_data: