sequenceDiagram
  autonumber
  participant Attacker
  participant PushProvider as Push Provider
  participant User

  Attacker->>PushProvider: send push request
  PushProvider-->>User: push notification
  User-->>PushProvider: ignore request
  loop repeated
    Attacker->>PushProvider: send push request
    PushProvider-->>User: push notification flood
  end
  User->>PushProvider: approve from fatigue
  PushProvider-->>Attacker: access granted
